"""
Step 1: generate the brainstorming essays.

Each model in config.MODELS is asked, config.N_REPETITIONS times, to write a
brainstorming report on human genome editing. Every essay is stored as its own
JSON file together with the full provenance needed to reproduce or audit it:
the exact prompt text, its hash, the sampling parameters, the provider that
actually served the request, and the token usage.

The script is resumable. Essays already on disk are skipped, so an interrupted
run can simply be restarted, and a single failed essay can be regenerated by
deleting its file.

Usage:
    python src/generate.py                          # anything still missing
    python src/generate.py --smoke                  # one essay from one model,
                                                    # to check credentials
    python src/generate.py --overwrite              # regenerate from scratch
    python src/generate.py --prompt brainstorm_generic   # the other condition
"""

import argparse
import hashlib
import json
import os
import random
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime, timezone

from dotenv import load_dotenv
from openai import OpenAI

import config


def build_client() -> OpenAI:
    """Create an OpenRouter-backed OpenAI client using the key from .env."""
    load_dotenv(config.ROOT / ".env")
    api_key = os.environ.get("OPENROUTER_API_KEY")
    if not api_key:
        raise RuntimeError(
            "OPENROUTER_API_KEY not found. Expected it in the project's .env file."
        )
    return OpenAI(base_url="https://openrouter.ai/api/v1", api_key=api_key)


def load_prompt(prompt_name: str) -> str:
    """Read a prompt file from prompts/ and return its text."""
    path = config.PROMPT_DIR / f"{prompt_name}.txt"
    if not path.exists():
        raise FileNotFoundError(f"No prompt file at {path}")
    return path.read_text(encoding="utf-8").strip()


def model_slug(model: str) -> str:
    """Turn an OpenRouter model id into something usable as a filename."""
    return model.replace("/", "__")


def output_path(prompt_name: str, model: str, repetition: int):
    """Where the essay for one (prompt, model, repetition) combination lives."""
    directory = config.GENERATED_DIR / prompt_name
    return directory / f"{model_slug(model)}__rep{repetition:02d}.json"


def generate_one(client: OpenAI, model: str, prompt: str) -> dict:
    """
    Send one generation request, retrying with exponential backoff on failure.

    Returns a dict with the essay text and everything worth recording about how
    it was produced. Raises if every attempt fails.
    """
    extra_body = {"reasoning": {"enabled": True}} if config.ENABLE_REASONING else {}

    last_error = None
    for attempt in range(config.MAX_RETRIES):
        try:
            response = client.chat.completions.create(
                model=model,
                messages=[{"role": "user", "content": prompt}],
                temperature=config.TEMPERATURE,
                extra_body=extra_body,
            )
            message = response.choices[0].message

            # Reasoning traces are kept for the record but never analysed: the
            # experiment is about the text the model presents to a user.
            reasoning = getattr(message, "reasoning", None)

            return {
                "content": message.content,
                "reasoning": reasoning,
                "generation_id": response.id,
                # Which upstream provider OpenRouter routed to. Worth recording,
                # since the same open-weight model can be served by different
                # providers at different quantisations.
                "provider": getattr(response, "provider", None),
                "usage": response.usage.model_dump() if response.usage else None,
            }

        except Exception as error:  # noqa: BLE001 - we retry on anything transient
            last_error = error
            if attempt < config.MAX_RETRIES - 1:
                # Exponential backoff with jitter, so parallel workers that hit a
                # rate limit together do not retry in lockstep.
                delay = 2**attempt + random.uniform(0, 1)
                print(f"  [{model}] attempt {attempt + 1} failed ({error}); "
                      f"retrying in {delay:.1f}s")
                time.sleep(delay)

    raise RuntimeError(f"All {config.MAX_RETRIES} attempts failed for {model}") from last_error


def run_task(client: OpenAI, prompt: str, prompt_name: str, model: str,
             repetition: int) -> str:
    """Generate one essay and write it to disk. Returns a short status string."""
    path = output_path(prompt_name, model, repetition)
    result = generate_one(client, model, prompt)

    if not result["content"] or not result["content"].strip():
        raise RuntimeError(f"{model} rep {repetition} returned empty content")

    record = {
        # --- identity -----------------------------------------------------
        "model": model,
        "repetition": repetition,
        "prompt_name": prompt_name,
        # --- provenance ---------------------------------------------------
        "prompt_text": prompt,
        "prompt_sha256": hashlib.sha256(prompt.encode("utf-8")).hexdigest(),
        "temperature": config.TEMPERATURE,
        "reasoning_enabled": config.ENABLE_REASONING,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "generation_id": result["generation_id"],
        "provider": result["provider"],
        "usage": result["usage"],
        # --- payload ------------------------------------------------------
        "essay": result["content"].strip(),
        "reasoning": result["reasoning"],
    }

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(record, indent=2, ensure_ascii=False), encoding="utf-8")

    words = len(record["essay"].split())
    return f"OK   {model} rep {repetition:02d}  ({words} words) -> {path.name}"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--overwrite", action="store_true",
                        help="regenerate essays even if they already exist")
    parser.add_argument("--smoke", action="store_true",
                        help="generate a single essay from the first model only")
    config.add_prompt_argument(parser)
    args = parser.parse_args()

    client = build_client()
    prompt_name = config.apply_overrides(args)
    prompt = load_prompt(prompt_name)

    models = config.MODELS[:1] if args.smoke else config.MODELS
    repetitions = 1 if args.smoke else config.N_REPETITIONS

    # Build the list of essays still to generate.
    tasks = [
        (model, repetition)
        for model in models
        for repetition in range(1, repetitions + 1)
        if args.overwrite or not output_path(prompt_name, model, repetition).exists()
    ]

    total = len(models) * repetitions
    print(f"Prompt: {prompt_name} "
          f"(sha256 {hashlib.sha256(prompt.encode()).hexdigest()[:12]})")
    print(f"Models: {len(models)} x {repetitions} repetitions = {total} essays")
    print(f"{total - len(tasks)} already on disk, {len(tasks)} to generate.\n")

    if not tasks:
        print("Nothing to do.")
        return

    failures = []
    with ThreadPoolExecutor(max_workers=config.MAX_WORKERS) as pool:
        futures = {
            pool.submit(run_task, client, prompt, prompt_name, model, repetition):
                (model, repetition)
            for model, repetition in tasks
        }
        for future in as_completed(futures):
            model, repetition = futures[future]
            try:
                print(future.result())
            except Exception as error:  # noqa: BLE001 - report and keep going
                failures.append((model, repetition, error))
                print(f"FAIL {model} rep {repetition:02d}: {error}")

    print(f"\nDone. {len(tasks) - len(failures)} generated, {len(failures)} failed.")
    if failures:
        print("Re-run this script to retry the failures.")


if __name__ == "__main__":
    main()
